#!/bin/bash
rm executable
rm -rf executable.dSYM # macOS generated output

clear
g++ -pg main.cpp -o executable -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio -lsfml-network -lstdc++

./executable

gprof executable gmon.out
