#!/bin/bash
clear
g++ -g -Wall main.cpp -o executable -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio -lsfml-network
./executable
rm executable
rm -rf executable.dSYM # macOS generated output
